### ISSUE TITLE
Feature Request: Regular Search on Glossary Page

### ISSUE THREAD

**Issue by albinomouse** [petereigenschink/glossary-confluence-cloud-issues#1]
Is it possible to add regular (non-CQL) search to the glossary page in Confluence cloud? We have non technical users who prefer the regular full text search and do not know how to use CQL-based search.

Eg. Typing "Mar" or "Market" should regular the glossary term "Market Order". At the moment, they have to type "text ~market".
<img width="1251" alt="screen shot 2017-11-12 at 7 19 17 pm" src="https://user-images.githubusercontent.com/1869092/32705143-a7a6e028-c7de-11e7-8479-d7bf4cefbbf4.png">

**Comment by petereigenschink** [comment]
This is certainly a good idea and I will check how the search is currently used most frequently.
Depending on that one of the following options will be included in the next release of the add-on:
- The search box is completely replaced by a regular search box
- The type of the search box can be configured for your Confluence instance
- It can be switched between regular and extended search (maybe along with issue #2)

**Comment by petereigenschink** [comment]
In the space glossary view now there is a settings dialog where you can switch between regular search and CQL search. The default option is regular.
