### ISSUE TITLE
Feature request: Sorting on Glossary Page

### ISSUE THREAD

**Issue by albinomouse** [petereigenschink/glossary-confluence-cloud-issues#2]
Could there be a configuration option to display "All" in a sorted order? At the moment, I believe the only way to sort "All" is to use CQL but this will not work for our non technical business users. I would like to be able to configure the glossary add-on to always display "All" alphabetically instead of in order of last modification. 

e.g. The attached screenshot should show in order - Accumulation Distribution, Advanced Decline Line, Market Order.

<img width="657" alt="screen shot 2017-11-12 at 7 25 54 pm" src="https://user-images.githubusercontent.com/1869092/32705199-54401016-c7df-11e7-94ab-71351c8d46cc.png">

**Comment by petereigenschink** [comment]
You are right, at the moment the only option to sort "All" is by using CQL, so your suggestion would definitely be an improvement. Depending on what fits best with the solution of issue #1, one of the following options will be included in the next release:
- The sort criteria for the glossary can be configured for your Confluence instance
- There will be some kind of sort option directly available in the glossary (maybe along with issue #1)

**Comment by petereigenschink** [comment]
In the space glossary view now there is a settings dialog where you can switch between different orderings. The default option is sort by modification date descending, but you can also switch between modification date and title and between ascending and descending.
