### ISSUE TITLE
Apostrophe in term gets improperly escaped in term list

### ISSUE THREAD

**Issue by kapluni** [petereigenschink/glossary-confluence-cloud-issues#6]
![screenshot](https://photos-1.dropbox.com/t/2/AADrsGiUt7drTtdNjSmPrsMw8Wq_vFlhKZvKBLvUhbiBZg/12/2759041/png/32x32/3/1522267200/0/2/Screenshot%202018-03-28%2011.05.18.png/EOaIjgIYwaQbIAIoAg/wAQDAQjpqKpLXl6UdQbkwSjbjF-8QW9JPrcgHlIDfnk?dl=0&preserve_transparency=1&size=2048x1536&size_mode=3)

Apostrophe gets shown as `&#39;`

**Comment by petereigenschink** [comment]
The issue is resolved an deployed, special characters are displayed as expected now.
