### ISSUE TITLE
How to add A-Z confluence page?

### ISSUE THREAD

**Issue by stefancvetkovic** [petereigenschink/glossary-confluence-cloud-issues#7]
I've installed add-on.
How to add A-Z confluence page?

**Comment by petereigenschink** [comment]
What exactly do you mean by a A-Z confluence page?

**Comment by stefancvetkovic** [comment]
I've installed on my OnCloud Confluence.
I can clearly see your add-on glossary on main Settings tab. 
Also in each space I can also see Glossary.

Now I want to add page to my space for example TechGlossary. From macro I can see only Glossary page, that renders HTML (3 sections) something that I do not need. 

I want something like this:
<img width="556" alt="2018-08-26 20_22_05-glossary for confluence cloud _ atlassian marketplace" src="https://user-images.githubusercontent.com/13699747/44631537-d41d0080-a96d-11e8-9017-5e7b9b3a640a.png">

Also I multiple times have read you guide, but I didn't succeed. 
The add-on like very good from images, and my organization would pay for it, but unfortunately I can't set it up.

**Comment by stefancvetkovic** [comment]
Dear Sir,

I am keen to buy your add-on Glossary but I have difficulties to configure it.
I want to create a Glossary Tech page.
like this:
2018-08-26 20_22_05-Glossary for Confluence Cloud _ Atlassian Marketplace.png
I need instructions how to properly set it up.

Global glossary is empty:
image.png

In current space:
image.png

But when I create new page, in macros I only see:
image.png

When I insert this only macro that I have, I see page like this:
image.png

I want this:
<img width="556" alt="2018-08-26 20_22_05-glossary for confluence cloud _ atlassian marketplace" src="https://user-images.githubusercontent.com/13699747/44631844-fadd3600-a971-11e8-82e2-cd46294c265f.png">


Regards,
Stefan Cvetkovic

**Comment by petereigenschink** [comment]
As I think we figured out everything via email and the solution was reinstalling the add-on, I close this issue. Please open another issue if you experience any other problems.
