### ISSUE TITLE
Space glossary not showing global terms

### ISSUE THREAD

**Issue by psteffek** [petereigenschink/glossary-confluence-cloud-issues#8]
Based on the documentation, I expected terms in a global glossary to show up in the glossary for a space. This does not appear to be working...

**Comment by petereigenschink** [comment]
Hey Phil,

I think there is a misunderstanding with the documentation. Terms in a global space glossary are visible in:
* The global glossary (the overview)
* All page glossaries across all spaces
* The highlighting by the browser extension
* The space glossary where the term has been created

So terms in global space glossaries are not supposed to be visible in other space glossaries.

**Comment by psteffek** [comment]
Thanks Peter. How do I access "The global glossary (the overview)"? Is there a URL i would go to?

Phil
________________________________

**Comment by petereigenschink** [comment]
The global glossary can be found in the general navigation bar:
<img src="https://user-images.githubusercontent.com/858766/47386435-f1bbdb80-d70c-11e8-9175-1a3a99c5ee0d.png" width="200"/>

To get there click on the Confluence icon in the top left corner.

Cheers

**Comment by petereigenschink** [comment]
Hey Phil,

Could we clarify your questions? If so, can I close this issue as resolved?

Cheers
