### ISSUE TITLE
Glossary search is not working

### ISSUE THREAD

**Issue by ghost** [petereigenschink/glossary-confluence-cloud-issues#9]
The page gets stuck and the wheel spinning endlessly.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/9619801/56187945-d6cb8380-602c-11e9-865b-123fb593b31a.png)

**Comment by ghost** [comment]
We are using Atlassian Cloud.

**Comment by petereigenschink** [comment]
I could reproduce the problem. The page gets stuck only if CQL search is active and you use an invalid CQL query for searching.
Instead you should receive a proper error message that the CQL query is invalid.

**Comment by petereigenschink** [comment]
Fix is now deployed. You will get better error messages when searching with an invalid CQL, also the page will not freeze.
